In [153]:
######Load .csv for Player_Summaries, Game_Publishers, Game_Genres, Game_Developers, Games_1 into PySpark dataframes.########
#import modules
from pyspark.sql import SparkSession
from pyspark.sql.types import *

#create session
spark = SparkSession.builder.getOrCreate()

##################################################Read games_1.csv ######################

# read csv file
games_1path="c:\dataset\games_1.csv"
games_1Dataframe = spark.read.csv(games_1path,header=True, inferSchema= True)

#show 10 rows of our DataFrame for games_1
print('Show 10 rows of our DataFrame for games_1:')
games_1Dataframe.show(10)

#count number of rows of our dataFrame for games_1
num_rows = games_1Dataframe.count()
print("Show number of rows of our DataFrame for games_1: ", num_rows)

#show our dataFrame schema for games_1
print('Show dataframe schema for our DataFrame for games_1:')
games_1Dataframe.printSchema()

#show statistics for the data we want for games_1
print('Show statistics for the data we want for games_1 playtime 2weeks:')
games_1Dataframe.describe('playtime_2weeks').show()

print('Show statistics for the data we want for games_1 playtime forever:')
games_1Dataframe.describe('playtime_forever').show()
###################################################### Read games_2.csv #####################

# read csv file
games_2path="c:\dataset\games_2.csv"
games_2Dataframe = spark.read.csv(games_2path,header=True, inferSchema= True)

#show 10 rows of our DataFrame for games_2
print('Show 10 rows of our dataframe for games_2:')
games_2Dataframe.show(10)

#count number of rows of our dataFrame for games_2
num_rows = games_2Dataframe.count()
print("Show number of rows of our dataframe for games_2: ", num_rows)

#show our dataFrame schema for games_2
print('Show our dataframe schema for games_2:')
games_2Dataframe.printSchema()

#show statistics for the data we want for games_2
print('Show statistics for the data we want for games_2 playtime 2weeks:')
games_2Dataframe.describe('playtime_2weeks').show()

print('Show statistics for the data we want for games_2 playtime forever:')
games_2Dataframe.describe('playtime_forever').show()
########################################### Read games_developers.csv######################  

# read csv file
games_developerspath="c:\dataset\games_developers.csv"
games_developersDataframe = spark.read.csv(games_developerspath,header=True, inferSchema= True)

#show 10 rows of our DataFrame for games_developers
print('Show 10 rows of our dataframe for games_developers:')
games_developersDataframe.show(10)


#count number of rows of our dataFrame for games_developers
num_rows = games_developersDataframe.count()
print("Show number of rows of our dataframe for games_developers: ", num_rows)

#show our dataFrame schema for games_developers
print('Show our dataframe schema for games_developers:')
games_developersDataframe.printSchema()

###################################### Read games_genres.csv################################
   
# read csv file
games_genrespath="c:\dataset\games_genres.csv"
games_genresDataframe = spark.read.csv(games_genrespath,header=True, inferSchema= True)

#show 10 rows of our DataFrame for games_genres
print('show 10 rows of our dataframe for games_genres:')
games_genresDataframe.show(10)

#count number of rows of our dataFrame for games_genres
num_rows = games_genresDataframe.count()
print('Show number of rows of our dataframe for games_genres: ', num_rows)

#show our dataFrame schema for games_genres
print('Show our dataframe for games_genres:')
games_genresDataframe.printSchema()

###################################################Read games_publishers.csv###############   

# read csv file
games_publisherspath="c:\dataset\games_publishers.csv"
games_publishersDataframe = spark.read.csv(games_publisherspath,header=True, inferSchema= True)

#show 10 rows of our DataFrame for games_publishers
print('Show 10 rows of our dataframe for games_publishers(about first 2600 rows of column publisher in the table is null ):')
games_publishersDataframe.show(10)

#one approach to remove Null  values from output
games_publishersDataframe.where(games_publishersDataframe.Publisher.isNotNull()).show(10)

#another approach to remove Null values from output
games_publishersDataframe = games_publishersDataframe.filter(games_publishersDataframe.Publisher.isNotNull())
games_publishersDataframe.show(20)



#count number of rows of our dataFrame for games_publishers
num_rows = games_publishersDataframe.count()
print('Show number of rows of our dataframe for games_publishers: ', num_rows)

#show our dataFrame schema for games_publishers
print('Show our dataframe schema for games_publishers:')
games_publishersDataframe.printSchema()

#############################################Read player_summaries.csv################


# read csv file
Player_Summariespath="c:\dataset\player_summaries.csv"
Player_SummariesDataframe=spark.read.csv(Player_Summariespath, header=True, inferSchema=True)
Player_SummariesDataframe.printSchema()

#show 10 rows of our DataFrame for player_summaries
print('Show 10 rows of our dataframe for player_summaries:')
Player_SummariesDataframe.show(10)

#count number of rows of our dataFrame for player_summaries
num_rows = Player_SummariesDataframe.count()
print('Show number of rows of our dataframe for player_summaries: ', num_rows)

#show our dataFrame schema for player_summaries
print('Show number of rows of our dataframe for player_summaries:')
Player_SummariesDataframe.printSchema()

#Create a new dataFrame from a subset of our existing dataFrame to remove unimportant columns
Player_SummariesDataframe2 = Player_SummariesDataframe.select(Player_SummariesDataframe['steamid'], Player_SummariesDataframe['lastlogoff'], Player_SummariesDataframe['primaryclanid'], Player_SummariesDataframe['timecreated'],
                         Player_SummariesDataframe['gameid'],Player_SummariesDataframe['gameserverip'],Player_SummariesDataframe['loccountrycode'],Player_SummariesDataframe['locstatecode'],Player_SummariesDataframe['loccityid'],Player_SummariesDataframe['dateretrieved'])

print('Show 10 rows of subset of our dataframe for player_summaries:')
Player_SummariesDataframe2.show(10)

#calculate the top 20 countries that have more players
Player_SummariesDataframe.groupBy("loccountrycode").count().sort("count",ascending=False).show()

Show 10 rows of our DataFrame for Exercise 1-2 games_1:
+-----------------+------+---------------+----------------+--------------------+
|          steamid| appid|playtime_2weeks|playtime_forever|       dateretrieved|
+-----------------+------+---------------+----------------+--------------------+
|76561198001291264|  8870|           null|            1392|2013-06-09 01:01:...|
|76561198001291264|   400|           null|             239|2013-06-09 01:01:...|
|76561198001291264|212910|           null|             130|2013-06-09 01:01:...|
|76561198001291264|   550|           null|           17547|2013-06-09 01:01:...|
|76561198001291264|   420|           null|             534|2013-06-09 01:01:...|
|76561198001291264|   380|           null|             290|2013-06-09 01:01:...|
|76561198001291264|   620|           null|             966|2013-06-09 01:01:...|
|76561198001291264|202990|              8|            1766|2013-06-09 01:01:...|
|76561198001291264|202970|           null|             807|2013-06-09 01:01:...|
|76561198001291264|   340|           null|              45|2013-06-09 01:01:...|
+-----------------+------+---------------+----------------+--------------------+
only showing top 10 rows

Show number of rows of our DataFrame for Exercise 1-2 games_1:  628117
Show dataframe schema for our DataFrame for Exercise 1-2 games_1:
root
 |-- steamid: long (nullable = true)
 |-- appid: integer (nullable = true)
 |-- playtime_2weeks: integer (nullable = true)
 |-- playtime_forever: integer (nullable = true)
 |-- dateretrieved: string (nullable = true)

Show statistics for the data we want for Exercise 1-2 games_1 playtime 2weeks:
+-------+------------------+
|summary|   playtime_2weeks|
+-------+------------------+
|  count|             29217|
|   mean|  521.026354519629|
| stddev|1061.9599689991494|
|    min|                 1|
|    max|             18576|
+-------+------------------+

Show statistics for the data we want for Exercise 1-2 games_1 playtime forever:
+-------+------------------+
|summary|  playtime_forever|
+-------+------------------+
|  count|            400549|
|   mean|2146.3125610100137|
| stddev|  9347.52520803799|
|    min|                 0|
|    max|            863378|
+-------+------------------+

Show 10 rows of our dataframe for Exercise 1-2 games_2:
+-----------------+------+---------------+----------------+--------------------+
|          steamid| appid|playtime_2weeks|playtime_forever|       dateretrieved|
+-----------------+------+---------------+----------------+--------------------+
|76561197973546950|    70|           null|              86|2014-08-16 18:25:...|
|76561197973532552| 65610|           null|               7|2014-08-16 18:26:...|
|76561197973497160|   280|           null|             731|2014-08-16 18:28:...|
|76561197973529600| 26800|           null|              39|2014-08-16 18:28:...|
|76561197973529600| 49540|           null|              95|2014-08-16 18:28:...|
|76561197973564668|202990|           null|             220|2014-08-16 18:29:...|
|76561197973537250| 32360|           null|             382|2014-08-16 18:30:...|
|76561197973542606|  8980|           null|              98|2014-08-16 18:31:...|
|76561197973542606|207530|           null|               6|2014-08-16 18:31:...|
|76561197973550976| 63910|              1|             916|2014-08-16 18:33:...|
+-----------------+------+---------------+----------------+--------------------+
only showing top 10 rows

Show number of rows of our dataframe for Exercise 1-2 games_2:  1200557
Show our dataframe schema for Exercise 1-2 games_2:
root
 |-- steamid: long (nullable = true)
 |-- appid: integer (nullable = true)
 |-- playtime_2weeks: integer (nullable = true)
 |-- playtime_forever: integer (nullable = true)
 |-- dateretrieved: string (nullable = true)

Show statistics for the data we want for Exercise 1-2 games_2 playtime 2weeks:
+-------+------------------+
|summary|   playtime_2weeks|
+-------+------------------+
|  count|             43616|
|   mean|  503.546657190022|
| stddev|1079.3843888439512|
|    min|                 1|
|    max|             20118|
+-------+------------------+

Show statistics for the data we want for Exercise 1-2 games_2 playtime forever:
+-------+------------------+
|summary|  playtime_forever|
+-------+------------------+
|  count|           1200557|
|   mean|1331.3431582173941|
| stddev| 8337.146026141538|
|    min|                 0|
|    max|            863378|
+-------+------------------+

Show 10 rows of our dataframe for Exercise 1-2 games_developers:
+------+---------+
| appid|Developer|
+------+---------+
|462530|       8i|
|452420|       M2|
|466530|       M2|
|366960|       UD|
|315060|      2SD|
|340200|      2SD|
|214610|      773|
|223890|      773|
|333220|      773|
|370280|      ???|
+------+---------+
only showing top 10 rows

Show number of rows of our dataframe for Exercise 1-2 games_developers:  19333
Show our dataframe schema for Exercise 1-2 games_developers:
root
 |-- appid: integer (nullable = true)
 |-- Developer: string (nullable = true)

show 10 rows of our dataframe for Exercise 1-2 games_genres:
+------+-----+
| appid|Genre|
+------+-----+
|  7290|  RPG|
|  8980|  RPG|
| 18010|  RPG|
| 18040|  RPG|
| 24447|  RPG|
| 73096|  RPG|
|213030|  RPG|
|216910|  RPG|
|225822|  RPG|
|228740|  RPG|
+------+-----+
only showing top 10 rows

Show number of rows of our dataframe for Exercise 1-2 games_genres:  39669
Show our dataframe for Exercise 1-2 games_genres:
root
 |-- appid: integer (nullable = true)
 |-- Genre: string (nullable = true)

Show 10 rows of our dataframe for Exercise 1-2 games_publishers(about first 2600 rows of column publisher in the table is null ):
+------+---------+
| appid|Publisher|
+------+---------+
|207990|     null|
|215220|     null|
|220824|     null|
|241600|     null|
|249310|     null|
|255060|     null|
|255251|     null|
|258347|     null|
|258409|     null|
|268313|     null|
+------+---------+
only showing top 10 rows

+------+---------+
| appid|Publisher|
+------+---------+
|340340|         |
|385770|         |
|345150|         |
|334690|         |
|334880|         |
|348110|         |
|270010|         |
|298280|        -|
|302230|        -|
|338746|       2K|
+------+---------+
only showing top 10 rows

+------+---------+
| appid|Publisher|
+------+---------+
|340340|         |
|385770|         |
|345150|         |
|334690|         |
|334880|         |
|348110|         |
|270010|         |
|298280|        -|
|302230|        -|
|338746|       2K|
|353830|       2K|
|341842|       2K|
|331330|       2K|
|341845|       2K|
|350414|       2K|
|453380|       2K|
|338470|       2K|
|341848|       2K|
|273350|       2K|
|289880|       2K|
+------+---------+
only showing top 20 rows

Show number of rows of our dataframe for Exercise 1-2 games_publishers:  16134
Show our dataframe schema for Exercise 1-2 games_publishers:
root
 |-- appid: integer (nullable = true)
 |-- Publisher: string (nullable = true)

root
 |-- steamid: long (nullable = true)
 |-- personaname: string (nullable = true)
 |-- profileurl: string (nullable = true)
 |-- avatar: string (nullable = true)
 |-- avatarmedium: string (nullable = true)
 |-- avatarfull: string (nullable = true)
 |-- personastate: integer (nullable = true)
 |-- communityvisibilitystate: integer (nullable = true)
 |-- profilestate: integer (nullable = true)
 |-- lastlogoff: timestamp (nullable = true)
 |-- commentpermission: integer (nullable = true)
 |-- realname: string (nullable = true)
 |-- primaryclanid: long (nullable = true)
 |-- timecreated: timestamp (nullable = true)
 |-- gameid: integer (nullable = true)
 |-- gameserverip: string (nullable = true)
 |-- gameextrainfo: string (nullable = true)
 |-- cityid: string (nullable = true)
 |-- loccountrycode: string (nullable = true)
 |-- locstatecode: string (nullable = true)
 |-- loccityid: integer (nullable = true)
 |-- dateretrieved: timestamp (nullable = true)

Show 10 rows of our dataframe for Exercise 1-2 player_summaries:
+-----------------+----------------+--------------------+--------------------+--------------------+--------------------+------------+------------------------+------------+-------------------+-----------------+-----------------+------------------+-------------------+------+------------+-------------+------+--------------+------------+---------+-------------------+
|          steamid|     personaname|          profileurl|              avatar|        avatarmedium|          avatarfull|personastate|communityvisibilitystate|profilestate|         lastlogoff|commentpermission|         realname|     primaryclanid|        timecreated|gameid|gameserverip|gameextrainfo|cityid|loccountrycode|locstatecode|loccityid|      dateretrieved|
+-----------------+----------------+--------------------+--------------------+--------------------+--------------------+------------+------------------------+------------+-------------------+-----------------+-----------------+------------------+-------------------+------+------------+-------------+------+--------------+------------+---------+-------------------+
|76561198024350932|        DGJarski|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       1|           1|2011-12-07 02:31:52|             null|             null|              null|               null|  null|        null|         null|  null|          null|        null|     null|2013-03-08 01:48:13|
|76561197972375740|         Kregger|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       1|           1|2013-02-18 03:53:19|             null|             null|              null|               null|  null|        null|         null|  null|          null|        null|     null|2013-02-28 14:38:19|
|76561197972581736|  3ulle+ C@+cher|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       3|           1|2011-08-29 18:36:52|             null|   Brandon Taylor|103582791429650487|2004-12-29 09:00:06|  null|        null|         null|  null|          null|        null|     null|2013-02-28 14:38:22|
|76561198027776732|ÐºÐ°Â®Ð»Â©Ð¾Ð½Â©|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       1|           1|2010-11-23 08:13:28|             null|             null|              null|               null|  null|        null|         null|  null|          null|        null|     null|2013-03-08 14:45:09|
|76561198080962334|         Djcs124|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       3|           1|2013-03-14 16:37:21|             null|Damian Cyr-Spence|103582791429521408|2013-01-08 13:54:23|  null|        null|         null|  null|          null|        null|     null|2013-03-14 23:02:27|
|76561198074103256|          SeconD|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       3|           1|2013-03-04 08:25:54|             null|             null|103582791429521408|2012-10-23 01:16:14|  null|        null|         null|  null|          null|        null|     null|2013-03-14 02:31:16|
|76561198001266978|       zainabwho|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       3|           1|2008-09-17 03:50:24|             null|           zainab|103582791430030453|2008-09-16 00:39:53|  null|        null|         null|  null|          null|        null|     null|2013-03-04 14:28:15|
|76561198028014428|         Jettoku|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       3|           1|2013-02-26 13:44:39|             null|             null|103582791430761860|2010-07-22 02:13:58|  null|        null|         null|  null|          null|        null|     null|2013-03-08 15:23:55|
|76561198000701276|      Shoop Boop|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       3|           1|2013-01-26 12:52:08|                1|            Robin|103582791429521408|2008-08-21 09:08:49|  null|        null|         null|  null|          null|        null|     null|2013-03-04 12:23:17|
|76561198024197968| DeserTT TiGeeR!|http://steamcommu...|http://media.stea...|http://media.stea...|http://media.stea...|           0|                       1|           1|2010-06-20 04:01:26|                2|             null|              null|               null|  null|        null|         null|  null|          null|        null|     null|2013-03-08 01:25:27|
+-----------------+----------------+--------------------+--------------------+--------------------+--------------------+------------+------------------------+------------+-------------------+-----------------+-----------------+------------------+-------------------+------+------------+-------------+------+--------------+------------+---------+-------------------+
only showing top 10 rows

Show number of rows of our dataframe for Exercise 1-2 player_summaries:  250000
Show number of rows of our dataframe for Exercise 1-2 player_summaries:
root
 |-- steamid: long (nullable = true)
 |-- personaname: string (nullable = true)
 |-- profileurl: string (nullable = true)
 |-- avatar: string (nullable = true)
 |-- avatarmedium: string (nullable = true)
 |-- avatarfull: string (nullable = true)
 |-- personastate: integer (nullable = true)
 |-- communityvisibilitystate: integer (nullable = true)
 |-- profilestate: integer (nullable = true)
 |-- lastlogoff: timestamp (nullable = true)
 |-- commentpermission: integer (nullable = true)
 |-- realname: string (nullable = true)
 |-- primaryclanid: long (nullable = true)
 |-- timecreated: timestamp (nullable = true)
 |-- gameid: integer (nullable = true)
 |-- gameserverip: string (nullable = true)
 |-- gameextrainfo: string (nullable = true)
 |-- cityid: string (nullable = true)
 |-- loccountrycode: string (nullable = true)
 |-- locstatecode: string (nullable = true)
 |-- loccityid: integer (nullable = true)
 |-- dateretrieved: timestamp (nullable = true)

Show 10 rows of subset of our dataframe for Exercise 1-2 player_summaries:
+-----------------+-------------------+------------------+-------------------+------+------------+--------------+------------+---------+-------------------+
|          steamid|         lastlogoff|     primaryclanid|        timecreated|gameid|gameserverip|loccountrycode|locstatecode|loccityid|      dateretrieved|
+-----------------+-------------------+------------------+-------------------+------+------------+--------------+------------+---------+-------------------+
|76561198024350932|2011-12-07 02:31:52|              null|               null|  null|        null|          null|        null|     null|2013-03-08 01:48:13|
|76561197972375740|2013-02-18 03:53:19|              null|               null|  null|        null|          null|        null|     null|2013-02-28 14:38:19|
|76561197972581736|2011-08-29 18:36:52|103582791429650487|2004-12-29 09:00:06|  null|        null|          null|        null|     null|2013-02-28 14:38:22|
|76561198027776732|2010-11-23 08:13:28|              null|               null|  null|        null|          null|        null|     null|2013-03-08 14:45:09|
|76561198080962334|2013-03-14 16:37:21|103582791429521408|2013-01-08 13:54:23|  null|        null|          null|        null|     null|2013-03-14 23:02:27|
|76561198074103256|2013-03-04 08:25:54|103582791429521408|2012-10-23 01:16:14|  null|        null|          null|        null|     null|2013-03-14 02:31:16|
|76561198001266978|2008-09-17 03:50:24|103582791430030453|2008-09-16 00:39:53|  null|        null|          null|        null|     null|2013-03-04 14:28:15|
|76561198028014428|2013-02-26 13:44:39|103582791430761860|2010-07-22 02:13:58|  null|        null|          null|        null|     null|2013-03-08 15:23:55|
|76561198000701276|2013-01-26 12:52:08|103582791429521408|2008-08-21 09:08:49|  null|        null|          null|        null|     null|2013-03-04 12:23:17|
|76561198024197968|2010-06-20 04:01:26|              null|               null|  null|        null|          null|        null|     null|2013-03-08 01:25:27|
+-----------------+-------------------+------------------+-------------------+------+------------+--------------+------------+---------+-------------------+
only showing top 10 rows

+--------------+------+
|loccountrycode| count|
+--------------+------+
|          null|224867|
|            US|  4832|
|            RU|  2839|
|            DE|  1636|
|            GB|  1242|
|            BR|  1239|
|            FR|  1100|
|            CA|   927|
|            PL|   652|
|            UA|   644|
|            AU|   609|
|            CN|   548|
|            SE|   510|
|            ES|   416|
|            DK|   360|
|            IT|   289|
|            PH|   274|
|            NO|   269|
|            CL|   266|
|            KR|   261|
+--------------+------+
only showing top 20 rows

In [152]:
################Join all `Games_` tables into one dataframe##################

from pyspark.sql import SQLContext
# first of all, I create an empty StructType
schema = StructType([])

#Create an empty dataframe based on the schema
joinedDF=sqlContext.createDataFrame(sc.emptyRDD(), schema)

#inner-join games_1Dataframe with games_2Dataframe based on their common column app_id and then assign the result to empty dataframe 
joinedDF=games_1Dataframe.join(games_2Dataframe, ['appid'])

#inner-join the result(joinedDF) with games_genresDataframe and assign to joinedDF
joinedDF=joinedDF.join(games_genresDataframe, ['appid'])

#inner-join the result(joinedDF) with games_publisherDataframe and assign to joinedDF
joinedDF=joinedDF.join(games_publishersDataframe, ['appid'])

#inner-join the result(joinedDF) with games_developerDataframe and assing the final result to joinedDF
joinedDF=joinedDF.join(games_developersDataframe,['appid'])

# show final result
joinedDF.show(10)

+-----+-----------------+---------------+----------------+--------------------+-----------------+---------------+----------------+--------------------+------+---------+--------------+
|appid|          steamid|playtime_2weeks|playtime_forever|       dateretrieved|          steamid|playtime_2weeks|playtime_forever|       dateretrieved| Genre|Publisher|     Developer|
+-----+-----------------+---------------+----------------+--------------------+-----------------+---------------+----------------+--------------------+------+---------+--------------+
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561198065327269|           null|             675|2014-09-18 20:10:...|Casual|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561198065327269|           null|             675|2014-09-18 20:10:...| Indie|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561197972327254|           null|             618|2014-08-16 13:37:...|Casual|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561197972327254|           null|             618|2014-08-16 13:37:...| Indie|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561198000881186|           null|            1226|2014-08-24 05:02:...|Casual|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561198000881186|           null|            1226|2014-08-24 05:02:...| Indie|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561197988824082|           null|              40|2014-08-19 08:47:...|Casual|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561197988824082|           null|              40|2014-08-19 08:47:...| Indie|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561197972577018|           null|              85|2014-08-16 15:09:...|Casual|     null|Unknown Worlds|
| 4900|76561197988824082|           null|              40|2013-05-22 08:29:...|76561197972577018|           null|              85|2014-08-16 15:09:...| Indie|     null|Unknown Worlds|
+-----+-----------------+---------------+----------------+--------------------+-----------------+---------------+----------------+--------------------+------+---------+--------------+
only showing top 10 rows

In [154]:
###################Count the number of games per `publisher` and per `genre`####################
# number of games per publisher using groupby, sorted descending to show the top 10 publishers
noGamesperPublisher = games_publishersDataframe.groupBy("publisher").count().sort("count", ascending=False)

print('Number of game per publisher:')
noGamesperPublisher.show(10)

#number of games per genre using groupby, sorted descending to show the top 10 genres
noGamesperGenres = games_genresDataframe.groupBy("genre").count().sort("count", ascending=False)

print('Number of games per genre:')
noGamesperGenres.show(10)

Number of game per publisher:
+--------------------+-----+
|           publisher|count|
+--------------------+-----+
|             Ubisoft|  384|
|                SEGA|  349|
|Dovetail Games - ...|  279|
| Paradox Interactive|  246|
|  Disney Interactive|  226|
|          Activision|  221|
|Feral Interactive...|  221|
|              Degica|  190|
|        Nordic Games|  164|
|         Square Enix|  153|
+--------------------+-----+
only showing top 10 rows

Number of games per genre:
+--------------------+-----+
|               genre|count|
+--------------------+-----+
|               Indie| 7982|
|              Action| 7126|
|           Adventure| 4517|
|            Strategy| 3953|
|              Casual| 3939|
|          Simulation| 3870|
|                 RPG| 3147|
|        Free to Play| 1172|
|        Early Access|  901|
|Massively Multipl...|  748|
+--------------------+-----+
only showing top 10 rows

In [156]:
####Find day and hour when most new accounts were created (based on Player_Summaries table) e.g. 8pm on 14th August 2005.#####
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *

#create session and read csv file
spark = SparkSession.builder.getOrCreate()
Player_Summariespath="c:\dataset\Player_Summaries.csv"
Player_SummariesDF=spark.read.csv(Player_Summariespath, header=True)

#sort column timecreated from newest to oldest
sorted_Player_SummariesDF = Player_SummariesDF.orderBy('timecreated',ascending=False) 

#get timecreated column from the dataframe
sorted_Player_SummariesDF_time = sorted_Player_SummariesDF.select("timecreated")

#check dataframe schema to make sure the above line works
sorted_Player_SummariesDF_time.printSchema()


#splitting the timestamp column to 2 columns (date, hour)
Player_SummariesDF_timestamp=sorted_Player_SummariesDF_time.select(
    to_date('timecreated').alias('date'),
    hour("timecreated").alias('hour')
)

#check dataframe schema to make sure spliting works
Player_SummariesDF_timestamp.printSchema()

# group dataframe by date to find the most created account date
Player_SummariesDF_grouped=Player_SummariesDF_timestamp.groupby('date').agg({'date': 'count'})

#order by the results descending
Player_SummariesDF_ordered=Player_SummariesDF_grouped.orderBy('count(date)', ascending=False)

# show the 10 first rows
Player_SummariesDF_ordered.show(10)

#find the most created account date using max
Player_SummariesDF_max=Player_SummariesDF_ordered.agg({'count(date)':'max'})

print('Max number of accounts created in one day is:')
Player_SummariesDF_max.show()

#this time, sort the dataframe by date to find the the most created account date
Player_SummariesDF_date=Player_SummariesDF_ordered.select(Player_SummariesDF_ordered['date'])

# pick the first row of the sorted dataframe (the most created account date)
Player_SummariesDF_first=Player_SummariesDF_date.first()

#compare the date column in the original dataframe with the most created account date 
#to filter other dates and assign it to a new dataframe 
Day_Most_Created=Player_SummariesDF_timestamp.where(Player_SummariesDF_timestamp.date == Player_SummariesDF_first.date)

#this time, group the dataframe by hour to find the most created account hour
Day_Most_Grouped=Day_Most_Created.groupby('hour').agg({'hour':'count'})

#sort the results descending
Hour_Most_Created=Day_Most_Grouped.orderBy('count(hour)', ascending=False)
Hour_Most_Created.show(10)

#now, find the most created account hour using max
Most_Created=Day_Most_Grouped.agg({'count(hour)':'max'})

print('Max number of accounts created in one hour in that specified date is:')
Most_Created.show()

#get data frame column value as variable
most_hour = Hour_Most_Created.select('hour').collect()[0].asDict()['hour']
print('The hour when most new accounts were created:', most_hour)

#get data frame column value as variable
most_date = Day_Most_Created.select('date').collect()[0].asDict()['date']
print('The date when most new accounts were created:', most_date)

root
 |-- timecreated: string (nullable = true)

root
 |-- date: date (nullable = true)
 |-- hour: integer (nullable = true)

+----------+-----------+
|      date|count(date)|
+----------+-----------+
|2012-12-25|       3682|
|2012-11-28|       3366|
|2012-12-26|       2691|
|2012-12-24|       2634|
|2012-12-22|       2508|
|2012-11-24|       2484|
|2012-12-27|       2415|
|2013-03-09|       2268|
|2012-12-23|       2252|
|2012-11-23|       2232|
+----------+-----------+
only showing top 10 rows

Max number of accounts created in one day is:
+----------------+
|max(count(date))|
+----------------+
|            3682|
+----------------+

+----+-----------+
|hour|count(hour)|
+----+-----------+
|  10|        292|
|   8|        279|
|  11|        230|
|   7|        208|
|   4|        208|
|  13|        203|
|  12|        193|
|   6|        192|
|   5|        190|
|   3|        178|
+----+-----------+
only showing top 10 rows

Max number of accounts created in one hour in that specified date is:
+----------------+
|max(count(hour))|
+----------------+
|             292|
+----------------+

The hour when most new accounts were created: 10
The date when most new accounts were created: 2012-12-25